# -*- coding: utf-8 -*-
"""submission_project_pertama_ml_terapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJfBxqydaXLlVm9LU4hpDJr3XW_kgUCq

# Domain Proyek

Diabetes merupakan penyakit kronis yang memengaruhi jutaan orang di seluruh dunia. Penyakit ini ditandai dengan tingginya kadar gula darah (glukosa) dalam tubuh. Kondisi ini terjadi karena tubuh tidak mampu memproduksi atau menggunakan hormon insulin secara efektif, sehingga glukosa tidak dapat digunakan sebagai sumber energi oleh sel-sel tubuh. Deteksi dini penyakit diabetes sangat penting untuk mencegah komplikasi yang lebih serius dan dapat dilakukan penanganan awal. Oleh karena itu, pengembangan model prediksi diabetes berbasis machine learning dapat membantu dalam diagnosis awal dan langkah yang diperlukan setelahnya.

Referensi:  
- [American Diabetes Association (2020). Classification and Diagnosis of Diabetes: Standards of Medical Care in Diabetes—2020.](https://doi.org/10.2337/dc20-S002)
- [D. Sisodia and D. S. Sisodia, “Prediction of Diabetes using Classification Algorithms,” Procedia Comput. Sci., vol. 132, pp. 1578–1585, 2018, doi: 10.1016/j.procs.2018.05.122.](https://doi.org/10.32520/stmsi.v10i1.1129)

# Business Understanding

## Problem Statements
- Bagaimana memprediksi apakah seseorang berisiko diabetes berdasarkan data medisnya?
- Bagaimana memanfaatkan model prediksi tersebut untuk membantu tenaga medis dalam pengambilan keputusan?

## Goals
- Membuat model klasifikasi yang dapat memprediksi risiko diabetes dengan akurasi tinggi.
- Membandingkan performa beberapa algoritma untuk menentukan model terbaik.

## Solution Statements
- Membangun baseline model menggunakan Logistic Regression dan Random Forest.
- Melakukan hyperparameter tuning pada model terbaik untuk meningkatkan performa.

# Data Understanding

#### Deskripsi Dataset

Dataset ini berisi data mengenai pasien yang memiliki atau berisiko mengalami diabetes. Setiap baris mewakili satu pasien, dan terdapat berbagai fitur medis yang diukur untuk setiap individu.

Dataset ini mencakup **768 entri** data dengan **12 kolom** fitur. Dataset ini memiliki label kelas yang mengindikasikan status diabetes pasien, yaitu **Non-diabetic (N)**, **Prediabetic (P)**, atau **Diabetic (Y)**.

#### Sumber Dataset
Dataset ini dapat ditemukan di [Kaggle - Diabetes Prediction Dataset](https://www.kaggle.com/datasets/marshalpatel3558/diabetes-prediction-dataset-legit-dataset/data?select=Dataset+of+Diabetes+.csv).

#### Variabel pada Dataset

1. **ID**: Identifikasi unik untuk setiap record pasien.
2. **No_Pation**: Nomor identifikasi pasien (mungkin ID rekam medis atau nomor pasien).
3. **Gender**: Jenis kelamin pasien:
   - `F`: Perempuan
   - `M`: Laki-laki
4. **AGE**: Usia pasien dalam tahun.
5. **Urea**: Tingkat urea dalam darah pasien (mg/dL atau mmol/L). Urea adalah produk sampingan metabolisme protein dan dapat memberikan indikasi fungsi ginjal.
6. **Cr**: Tingkat kreatinin dalam darah (mg/dL atau µmol/L). Kreatinin juga merupakan indikator fungsi ginjal.
7. **HbA1c**: Hemoglobin terglikasi, yang menunjukkan rata-rata kadar gula darah pasien selama 2-3 bulan terakhir (dalam bentuk persentase).
8. **Chol**: Kadar kolesterol total dalam darah (mg/dL atau mmol/L).
9. **TG**: Kadar trigliserida dalam darah (mg/dL atau mmol/L). Trigliserida adalah jenis lemak dalam darah.
10. **HDL**: Kadar kolesterol high-density lipoprotein (HDL), sering disebut sebagai kolesterol "baik" (mg/dL atau mmol/L).
11. **LDL**: Kadar kolesterol low-density lipoprotein (LDL), sering disebut sebagai kolesterol "jahat" (mg/dL atau mmol/L).
12. **VLDL**: Kadar kolesterol very low-density lipoprotein (VLDL), yang juga merupakan jenis kolesterol (mg/dL atau mmol/L).
13. **BMI**: Indeks massa tubuh (BMI), yang mengukur proporsi lemak tubuh berdasarkan tinggi badan dan berat badan (kg/m²).
14. **CLASS**: Label status diabetes dari pasien:
    - `N`: Non-diabetic
    - `P`: Prediabetic
    - `Y`: Diabetic

---

# Import Library and Data Load
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler

from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Coding Camp - DBS Fundation/Machine Learning Terapan/Submission Pertama/Dataset of Diabetes .csv')
df.head()

"""# EDA (Exploratory Data Analysis)"""

df.shape

"""fungsi `df.shape` bertujuan untuk melihat jumlah row dan kolom pada sebuah DataFrame.Pada dataset tersebut memiliki total **1000** row dan **14** kolom"""

df.info()

"""`df.info()` memberikan informasi mengenai tipe data dan jumlah data yang hilang (missing values) untuk setiap kolom.

Pada dataset tersebut memiliki **13** tipe data berbentuk **float** dan **int**, lalu **1** tipe data berbentuk **object** yaitu 'class' yang mana ini merupakan **target** pada dataset ini.

Fungsi ini juga menunjukan bahwa pada dataset ini tidak memiliki **missing value** ditunjukkan pada *non-null*
"""

df.describe()

"""Fungsi `describe()` memberikan informasi statistik pada masing-masing kolom, antara lain:

- `Count`  adalah jumlah sampel pada data.
- `Mean` adalah nilai rata-rata.
- `Std` adalah standar deviasi.
- `Min` yaitu nilai minimum setiap kolom.
- `25%` adalah kuartil pertama. Kuartil adalah nilai yang menandai batas interval dalam empat bagian sebaran yang sama.
- `50%` adalah kuartil kedua, atau biasa juga disebut median (nilai tengah).
- `75%` adalah kuartil ketiga.
- `Max` adalah nilai maksimum.

dari fungsi `describe()` kita dapat mengetahui beberapa informasi :

- **AGE**: Usia pasien rata-rata 53.5 tahun, dengan variasi antara 20 hingga 79 tahun.
- **Urea** dan **Cr (Kreatinin)**: Kadar urea dan kreatinin menunjukkan rentang yang cukup besar, yang dapat memberikan indikasi mengenai fungsi ginjal pasien.
- **HbA1c**: Rata-rata kadar HbA1c sebesar 8.28% menunjukkan bahwa banyak pasien memiliki kadar gula darah lebih tinggi dari batas normal (6.5%).
- **Kolesterol (Chol, TG, HDL, LDL, VLDL)**: Kolesterol total, trigliserida, HDL, LDL, dan VLDL menunjukkan variasi yang cukup besar, yang dapat mempengaruhi kesehatan jantung.
- **BMI**: Rata-rata BMI adalah 29.58, yang menunjukkan bahwa sebagian besar pasien termasuk dalam kategori overweight atau obesitas.

## Menangani Missing Values
"""

df.isnull().sum()

"""`df.isnull().sum()` merupakan fungsi untuk mengetahui kolom kolom yang memiliki missing values , pada dataset tersebut **tidak** ditemukan data yang **kosong**

## Menangani Outliers
"""

plt.figure(figsize=(15, 12))

n_cols = len(df.columns)
n_rows = (n_cols + 3) // 4

for i, column in enumerate(df.columns, 1):
    plt.subplot(n_rows, 4, i)
    sns.boxplot(df[column])
    plt.title(f'Boxplot {column}')

plt.tight_layout()
plt.show()

"""Boxplot yang ditampilkan menunjukkan beberapa fitur dalam dataset yang memiliki outliers yang terdeteksi. Outliers ini ditunjukkan dengan titik di luar whiskers pada setiap boxplot. Berikut adalah penjelasan mengenai fitur-fitur yang memiliki outliers:

1. **Boxplot Gender**:
   - Kolom **Gender** tidak menunjukkan adanya outliers karena hanya berisi dua kategori (`M` dan `F`).
   - Oleh karena itu, tidak ada distribusi yang perlu dianalisis lebih lanjut pada kolom ini.

2. **Boxplot Urea dan Boxplot Cr**:
   - **Urea** dan **Creatinine (Cr)** menunjukkan adanya nilai yang sangat tinggi yang berada di luar whiskers.
   - Nilai outliers pada kolom ini bisa mengindikasikan masalah pada fungsi ginjal, namun perlu dianalisis lebih lanjut apakah ini merupakan data yang sah atau kesalahan dalam pencatatan.

3. **Boxplot HbA1c**:
   - Kolom **HbA1c** menunjukkan adanya outliers dengan nilai yang sangat tinggi, yang menunjukkan bahwa beberapa pasien mungkin memiliki kadar gula darah yang sangat tidak terkontrol.
   - Pasien dengan nilai HbA1c tinggi mungkin menunjukkan kondisi diabetes yang buruk dan membutuhkan perhatian medis lebih lanjut.

4. **Boxplot Chol, TG, HDL, LDL, VLDL**:
   - Kolom **Cholesterol (Chol)**, **Triglycerides (TG)**, **HDL**, **LDL**, dan **VLDL** menunjukkan adanya outliers yang dapat dikaitkan dengan masalah kesehatan kardiovaskular.
   - Outliers pada kadar kolesterol dan trigliserida dapat menunjukkan pasien dengan risiko penyakit jantung atau gangguan metabolik, yang merupakan indikasi penting dalam diagnosis dan perawatan.

Kesimpulan:
- Outliers pada **AGE**, **Urea**, **Creatinine**, **HbA1c**, dan kolesterol menunjukkan adanya variasi yang signifikan dalam kondisi medis pasien.
- Beberapa nilai outliers mungkin merupakan data yang sah, misalnya pada pasien dengan gangguan ginjal atau diabetes yang tidak terkontrol.
- Pada dataset ini kita asumsikan bahwa data tersebut memang apa adanya karena dalam dunia medis sering ditemukan outliers pada beberapa fitur

"""

numerical_cols = ['AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL', 'BMI']
categorical_cols = ['Gender', 'CLASS']

"""## Categorical Features"""

feature = categorical_cols[0]
count = df[feature].value_counts()
percent = 100*df[feature].value_counts(normalize=True)
categorical_df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(categorical_df)
count.plot(kind='bar', title=feature);

"""pada kolom `gender` menunjukkan perbandingan yang hampir seimbang yaitu untuk **Male** sebanyak **565** data dan untuk **Female** sebanyak **435**. Namun terdapat kesalahan penulisan pada salah satu data yaitu menggunakan huruf kecil pada `f` yang mana ini menunjukkan inkonsistensi. Maka perlu dirubah agar data menjadi konsisten"""

feature = categorical_cols[1]
count = df[feature].value_counts()
percent = 100*df[feature].value_counts(normalize=True)
categorical_df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(categorical_df)
count.plot(kind='bar', title=feature);

"""pada kolom `CLASS` menunjukkan perbandingan yang yang tidak seimbang / imbalance yaitu untuk **Y** sebanyak **844** data, untuk **N** sebanyak **103**,dan untuk **P** sebanyak **53**. Namun terdapat beberapa data yang terjadi kesalahan penulisan yaitu `Y`  dan `N` ,yang mana ini menunjukkan inkonsistensi. Maka perlu dirubah agar data menjadi konsisten

## Numerical Features
"""

df[numerical_cols].hist(bins=50, figsize=(20,15))
plt.show()

"""Penjelasan Distribusi Histogram untuk Fitur Numerik

1. **AGE**:
   - Distribusi **AGE** cenderung memiliki dua puncak, dengan konsentrasi utama pada usia sekitar 40-50 tahun. Ini menunjukkan bahwa sebagian besar pasien berada pada kelompok usia menengah.
   - Ada beberapa pasien di usia yang lebih tua, tetapi secara umum, distribusinya lebih terpusat pada rentang usia menengah.

2. **Urea**:
   - Distribusi **Urea** menunjukkan konsentrasi yang lebih tinggi pada nilai yang lebih rendah, dengan banyak pasien memiliki kadar urea di sekitar 5 mg/dL.
   - Ada beberapa outliers dengan nilai urea yang sangat tinggi, yang bisa menunjukkan gangguan fungsi ginjal.

3. **Cr (Kreatinin)**:
   - Distribusi **Cr** menunjukkan puncak yang sangat tinggi di sekitar 100, dengan sebagian besar data terkonsentrasi di bawah 200 mg/dL.
   - Ada beberapa pasien dengan kadar kreatinin sangat tinggi, yang menunjukkan adanya masalah pada fungsi ginjal.

4. **HbA1c**:
   - **HbA1c** memiliki distribusi yang miring ke kanan, dengan banyak pasien memiliki nilai di bawah 8%.
   - Ini menunjukkan bahwa sebagian besar pasien berada dalam rentang prediabetes atau diabetes yang tidak terkontrol dengan kadar HbA1c yang lebih tinggi.

5. **Chol (Kolesterol Total)**:
   - Distribusi **Chol** cenderung normal, dengan puncak di sekitar 4-6 mg/dL. Namun, ada beberapa outliers dengan kadar kolesterol yang sangat tinggi.
   - Ini menunjukkan adanya variasi yang cukup besar dalam kadar kolesterol darah pasien.

6. **TG (Trigliserida)**:
   - Distribusi **TG** memiliki puncak di sekitar 2-3 mg/dL, dengan beberapa pasien memiliki kadar trigliserida yang sangat tinggi (outliers).
   - Peningkatan kadar trigliserida dapat mengindikasikan risiko penyakit kardiovaskular.

7. **HDL (Kolesterol HDL)**:
   - Distribusi **HDL** menunjukkan konsentrasi di bawah 2, dengan beberapa pasien memiliki kadar HDL yang lebih tinggi.
   - HDL adalah kolesterol "baik," dan sebagian besar pasien tampaknya memiliki kadar yang lebih rendah dari yang diinginkan (idealnya di atas 2 mg/dL).

8. **LDL (Kolesterol LDL)**:
   - Distribusi **LDL** menunjukkan konsentrasi yang lebih tinggi pada nilai rendah (sekitar 2-3 mg/dL), dengan beberapa outliers yang menunjukkan kadar LDL sangat tinggi.
   - Ini menunjukkan adanya risiko yang lebih tinggi terkait dengan kolesterol "jahat" dalam darah.

9. **VLDL**:
   - Distribusi **VLDL** menunjukkan puncak di sekitar nilai yang sangat rendah, dengan beberapa outliers pada nilai tinggi.
   - VLDL adalah jenis kolesterol yang berbahaya, dan distribusinya menunjukkan sebagian besar pasien memiliki kadar yang lebih rendah.

10. **BMI**:
   - Distribusi **BMI** menunjukkan bahwa sebagian besar pasien memiliki BMI di sekitar 25-30, yang menunjukkan kelompok pasien dengan kategori overweight atau obesitas.
   - Ada banyak variasi pada BMI, dengan beberapa pasien memiliki BMI yang lebih tinggi dari nilai normal (30 ke atas).

 Kesimpulan:
- **AGE**, **Urea**, **Cr**, **HbA1c**, dan **Chol** menunjukkan variasi yang cukup besar di antara pasien. Beberapa fitur, seperti **Urea**, **Cr**, dan **HbA1c**, menunjukkan puncak yang kuat, yang bisa mengindikasikan kondisi medis yang lebih serius pada sebagian pasien.
- Kolesterol dan trigliserida (**Chol**, **TG**, **HDL**, **LDL**, **VLDL**) menunjukkan variasi yang normal, tetapi dengan beberapa nilai ekstrem yang mungkin mencerminkan risiko kardiovaskular pada beberapa pasien.
- **BMI** menunjukkan bahwa sebagian besar pasien berada dalam kategori overweight atau obesitas, yang merupakan faktor risiko untuk diabetes.

# Data Preprocessing

## Menangani data inkonsisten
"""

df['Gender'].value_counts()

df['CLASS'].value_counts()

print(df['CLASS'].unique())

"""dari fungsi `unique()` menunjukkan bahwa terdapat karakter ' ' (spasi) pada nilai 'N ' dan 'Y ' , nanti akan dihilangkan karakter tambahan (spasi)"""

df['Gender'] = df['Gender'].replace({'f': 'F'})
df['Gender'].value_counts()

"""fungsi `replace()` pada `df['Gender'].replace({'f': 'F'}` merubah karakter 'f' menjadi 'F' agar sesuai dengan nilai utama"""

df['CLASS'] = df['CLASS'].replace({'Y ': 'Y', 'N ': 'N'})
df['CLASS'].value_counts()

"""fungsi `replace()` pada `df['CLASS'].replace({'Y ': 'Y', 'N ': 'N'})` merubah karakter 'Y ' dan 'N ' menjadi 'Y' dan 'N' agar sesuai dengan nilai utama

## Encoding Categorical
"""

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['CLASS'] = le.fit_transform(df['CLASS'])

"""`LabelEncoder()` digunakan untuk merubah nilai kategorikal menjadi bentuk dari **0 sampai banyaknya data -1**, karena pada *Gender* memiliki 2 nilai yaitu F dan M , maka dirubah menjadi F = 0 , M = 1. Sedangkan pada *CLASS* memiliki 3 nilai yaitu Y, N, dan P maka dirubah menjadi N= 0, P= 1, Y= 2"""

df.head()

"""## Drop Columns"""

df.drop(['ID', 'No_Pation'], axis=1, inplace=True)
df.head()

"""pada kolom `ID` dan `No_Pation` kita drop karena kolom ini tidak digunakan dalam proses modelling nanti

## Korelasi antar Fitur
"""

plt.figure(figsize=(10, 8))
correlation_matrix = df.corr().round(2)

# Untuk menge-print nilai di dalam kotak, gunakan parameter anot=True
sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5, )
plt.title("Correlation Matrix untuk Fitur Numerik ", size=20)

"""Berdasarkan hasil **korelasi matrix** , fitur yang memiliki keterkaitan yang kuat dengan target `CLASS` yaitu `BMI`, `HbA1C`, dan `AGE` . sedangkan kolom `VLDL`, `TG`, `Chol`, dan `Gender` memiliki keterkaitan dengan target namun lemah.

## Train - Test Split
"""

X = df.drop('CLASS', axis=1)
y = df['CLASS']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'Total # of sample in whole dataset: {len(X)}')
print(f'Total # of sample in train dataset: {len(X_train)}')
print(f'Total # of sample in test dataset: {len(X_test)}')

"""pada fungsi `train_test_split()` disini menerapkan **80:20** , yaitu dimana 80% digunakan sebagai data **train** dan 20% digunakan untuk data **test**

## SMOTE (Oversampling)
"""

y_train.value_counts()

smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print(y_train_resampled.value_counts())

"""`SMOTE(random_state=42)`: Fungsi SMOTE dengan nilai acak (random state) untuk memastikan hasil yang reproducible.

`smote.fit_resample(X_train, y_train)`: Fungsi ini melakukan oversampling pada X_train dan y_train dengan teknik SMOTE.

`y_train_resampled.value_counts()`: Menampilkan distribusi kelas setelah proses oversampling.
"""

# Menampilkan distribusi kelas setelah oversampling
import matplotlib.pyplot as plt

y_train_resampled.value_counts().plot(kind='bar')
plt.title('Distribusi Kelas Setelah Oversampling (SMOTE)')
plt.xlabel('Kelas')
plt.ylabel('Jumlah Data')
plt.show()

"""Hasil dari `SMOTE` dapat dilihat yaitu sekarang target menunjukkan sudah balance dengan masing masing memiliki nilai **671**

## Standardisasi
"""

scaler = StandardScaler()
X_train_resampled = scaler.fit_transform(X_train_resampled)
X_test = scaler.transform(X_test)

X_train_resampled

"""`StandardScaler` digunakan untuk menstandarisasi data agar fitur memiliki skala yang sama, dan ini diterapkan pada data latih yang sudah dioversampling dan data uji.

# Modelling

## Logistic Regression
"""

model_lr = LogisticRegression(random_state=42)
model_lr.fit(X_train_resampled, y_train_resampled)

# Melakukan prediksi pada data uji
y_pred_lr = model_lr.predict(X_test)

# Menilai model menggunakan metrik yang sesuai (misalnya, akurasi, precision, recall)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

"""pada model `Logistic Regression` hasil akurasi didapatkan mencapai **90%** dengan masing masing :

- pada **class** 0
  
  `presisi` : 67%

  `recall`  : 86%

  `f1-score` : 75%

- pada **class** 1
  
  `presisi` : 27%

  `recall`  : 67%

  `f1-score` : 38%

- pada **class** 2
  
  `presisi` : 100%

  `recall`  : 67%

  `f1-score` : 38%


Hasil ini menunjukkan bahwa model ini belum bisa mengenali pola secara merata khususnya untuk **class** bernilai 1 / Prediabetes

"""

# Menampilkan Confusion Matrix
cm = confusion_matrix(y_test, y_pred_lr)

# Plotting Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Non-diabetic', 'Diabetic', 'Prediabetic'], yticklabels=['Non-Diabetic', 'Diabetic','Prediabetic'])
plt.title('Confusion Matrix for Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""## Random Forest"""

model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train_resampled, y_train_resampled)

# Melakukan prediksi pada data uji
y_pred_rf = model_rf.predict(X_test)

# Menilai model menggunakan metrik yang sesuai (misalnya, akurasi, precision, recall)
from sklearn.metrics import accuracy_score
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

"""pada model `Random Forest` hasil akurasi didapatkan mencapai **90%** dengan masing masing :

- pada **class** 0
  
  `presisi` : 88%

  `recall`  : 100%

  `f1-score` : 93%

- pada **class** 1
  
  `presisi` : 100%

  `recall`  : 100%

  `f1-score` : 100%

- pada **class** 2
  
  `presisi` : 100%

  `recall`  : 98%

  `f1-score` : 99%


Hasil ini menunjukkan bahwa model ini sudah cukup baik untuk mengenali pola dari masing-masing nilai pada target.
"""

# Menampilkan Confusion Matrix
cm = confusion_matrix(y_test, y_pred_rf)

# Plotting Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Non-diabetic', 'Diabetic', 'Prediabetic'], yticklabels=['Non-Diabetic', 'Diabetic','Prediabetic'])
plt.title('Confusion Matrix for Random Forest')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

"""# Evaluasi Model"""

# Menghitung metrik evaluasi untuk kedua model
metrics = {
    'Model': ['Logistic Regression', 'Random Forest'],
    'Accuracy': [accuracy_score(y_test, y_pred_lr), accuracy_score(y_test, y_pred_rf)],
    'Precision': [precision_score(y_test, y_pred_lr, average='weighted'), precision_score(y_test, y_pred_rf, average='weighted')],
    'Recall': [recall_score(y_test, y_pred_lr, average='weighted'), recall_score(y_test, y_pred_rf, average='weighted')],
    'F1 Score': [f1_score(y_test, y_pred_lr, average='weighted'), f1_score(y_test, y_pred_rf, average='weighted')]
}

# Membuat DataFrame untuk membandingkan kedua model
df_comparison = pd.DataFrame(metrics)

df_comparison

"""perbandingan antara `Logistic Regression` dan `Random Forest` menunjukkan bahwa `Random Forest` lebih baik tingkat akurasinya yaitu sebesar **98 %**"""

data_baru = {
    'AGE': [45],          # Usia
    'Urea': [5.5],        # Kadar Urea dalam darah
    'Cr': [1.1],          # Kadar Kreatinin dalam darah
    'HbA1c': [7.5],       # Kadar HbA1c
    'Chol': [5.2],        # Kadar Kolesterol
    'TG': [2.3],          # Kadar Trigliserida
    'HDL': [1.1],         # Kadar HDL
    'LDL': [2.6],         # Kadar LDL
    'VLDL': [1.3],        # Kadar VLDL
    'BMI': [27.0],        # BMI
    'Gender': [0]         # Gender (0 untuk perempuan, 1 untuk laki-laki)
}
data_baru_df = pd.DataFrame(data_baru)

X_train_cols = X_train.columns
data_baru_df = data_baru_df[X_train_cols]

data_baru_standardisasi = scaler.transform(data_baru_df)

# Melakukan prediksi dengan model terbaik (Random Forest setelah tuning)
y_pred_baru = model_rf.predict(data_baru_standardisasi)

# Menampilkan hasil prediksi
if y_pred_baru == 0:
    print("Prediksi: Non-Diabetic")
elif y_pred_baru == 1:
    print("Prediksi: Diabetic")
else:
    print("Prediksi: Prediabetic")